import 'dart:ui';

class ColorPalette {
  static const Color primaryColor = Color(0xFF799336);
  static const Color primaryDisabledColor = Color(0xFF505444);
  static const Color whiteColor = Color(0xFFFFFFFF);
  static const Color blackColor = Color(0xFF000000);
  static const Color greyColor = Color(0xFFE0E0E0);
  static const Color textFieldBorderColor = Color(0xFFdcdde5);
  static const Color buttonDisabledColor = Color(0xFF959595);
  static const Color buttonEnabledColor = Color(0xFF2B2B2B);
  static const Color featureBackgroundColor = Color(0xFFeffcf8);
  static const Color diaryListBackgroundColor = Color(0xFFf6f6f6);
  static const Color orangeIconColor = Color(0xFFff7245);
  static const Color secondryTextColor = Color(0xFF8E8E8E);
  static const Color shadowColor = Color(0xFFf3f3f3);
  static const Color meronColor = Color(0xFF981f4d);
  static const Color darkBlueColor = Color(0xFF1e4e93);
  static const Color darkenScaffoldColor = Color(0xFFf5f5f5);
  static const Color darkGreyColor = Color(0xFFefeff4);
  static const Color red = Color(0xFFff0000);
  static const Color green = Color(0xFF01bb08);
  static const Color filterButtonGreyColor = Color(0xFF585D69);
  static const Color timerBackgroundColor = Color(0xFF0098DA);
  static const Color darkSkyBlue = Color(0xFF337AB7);
  static const Color lightOrange = Color(0xFFF0AD4E);
  static const Color darkOrange = Color(0xFFFF7245);
  static const Color darkRed = Color(0xFFE44501);
  static const Color pureGreen = Color(0xFF2EB700);
  static const Color lightGreen = Color(0xFF18FF00);
  static const Color materialBlue = Color(0xFF337AB7);
  static const Color lightGrey = Color(0xFF454B53);
  static const Color materialGreen = Color(0xFF0E8F2B);
  static const Color materialred = Color(0xFFC9320E);
  static const Color materialYellow = Color(0xFFDAA520);
  static const Color uploadBoxColor = Color(0xFFEFFCF8);
  static const Color pink = Color(0xFFFF5CA8);
  static const Color lightPink = Color(0xFFFFF0F0);
  static const Color lightRed = Color(0xFFF25F5F);
  static const Color diaryDescriptionColor = Color(0xFFFAF9F6);
  static const Color greyShade2 = Color(0xFF303030);
  static const Color greyShade3 = Color(0xFF808080);
}
